services:
  postgres:
    image: postgis/postgis:16-3.5-alpine
    container_name: osm-railways-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  railmap:
    image: railmap
    restart: always
    ports:
      - 3000:80

volumes:
  postgres_data:
